version: '3'

services:
  database:
    image: mariadb:lts
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: test_root_pw
      MARIADB_DATABASE: test-mariadb
      MARIADB_USER: test_user
      MARIADB_PASSWORD: test_pw
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
    - "./database.sql:/docker-entrypoint-initdb.d/1.sql"
  web:
    image: php:8.2-apache
    container_name: php_web
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./public/:/var/www/html/
    ports:
      - "127.0.0.1:8080:80"
    command: sh -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    #stdin_open: true
    #tty: true
